import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import { ArrowIcon, DirectoryIcon, FsdpIcon, WorkloadIcon } from "../components/Icons";
import { getFsdpSummary, getWorkloadSummary } from "../api";
import type { FsdpSummary, WorkloadSummary } from "../types";
import "./DashboardPage.css";

const hours=(value:number|undefined)=>value===undefined?"—":`${value.toFixed(1)} h`;
type Card={label:string;value:string|number;note:string;icon:typeof FsdpIcon;accent?:boolean;workload?:boolean};
function CardGrid({cards}:{cards:Card[]}){return <div className="analytics-grid">{cards.map(({label,value,note,icon:Icon,accent,workload})=><article className={`analytics-card ${accent?"accent":""} ${workload?"workload":""}`} key={label}><Icon/><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</div>}
export default function DashboardPage(){const[fsdp,setFsdp]=useState<FsdpSummary|null>(null);const[workload,setWorkload]=useState<WorkloadSummary|null>(null);useEffect(()=>{void getFsdpSummary().then(setFsdp).catch(()=>setFsdp(null));void getWorkloadSummary().then(setWorkload).catch(()=>setWorkload(null))},[]);const fsdpCards:Card[]=[{label:"Total scholar records",value:fsdp?.total??"—",note:"Development beneficiaries on file",icon:FsdpIcon},{label:"On-going programs",value:fsdp?.ongoing??"—",note:"Current development participation",icon:FsdpIcon,accent:true},{label:"Graduated",value:fsdp?.graduated??"—",note:"Completed development programs",icon:FsdpIcon}];const workloadCards:Card[]=[{label:"Workload records",value:workload?.workloads??"—",note:"Faculty teaching-load entries",icon:WorkloadIcon,workload:true},{label:"Course assignments",value:workload?.assignments??"—",note:"Subjects and sections scheduled",icon:WorkloadIcon,workload:true},{label:"Total weekly hours",value:hours(workload?.weekly_hours),note:`${hours(workload?.lecture_hours)} lecture · ${hours(workload?.laboratory_hours)} laboratory`,icon:WorkloadIcon,accent:true,workload:true}];return <div className="dashboard stack-lg"><section className="dashboard-hero"><div><span className="eyebrow light">CATHEDRA OVERVIEW</span><h1>Office operations, at a glance.</h1><p>Track development programs and faculty teaching loads from one local workspace.</p></div><div className="dashboard-status"><span/>Live local records</div></section><section><div className="dashboard-heading"><span className="eyebrow">FSDP STATISTICS</span><h2>Faculty & Staff Development</h2></div><CardGrid cards={fsdpCards}/></section><section><div className="dashboard-heading"><span className="eyebrow">WORKLOAD STATISTICS</span><h2>Teaching workload</h2></div><CardGrid cards={workloadCards}/></section><section className="dashboard-actions"><Link to="/fsdp" className="dashboard-action"><FsdpIcon/><div><strong>Manage FSDP records</strong><span>Review scholars, grants, and progress</span></div><ArrowIcon/></Link><Link to="/workload" className="dashboard-action"><WorkloadIcon/><div><strong>Review faculty workload</strong><span>Review teaching hours and assignments</span></div><ArrowIcon/></Link><Link to="/faculty-profiles" className="dashboard-action"><DirectoryIcon/><div><strong>Maintain faculty profiles</strong><span>Update appointments and salary details</span></div><ArrowIcon/></Link></section></div>}
