import { FormEvent, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getAccountStatus, saveSession, setupAdmin, signIn } from "../api";

export default function LoginPage() {
  const navigate = useNavigate(); const [setupRequired, setSetupRequired] = useState<boolean | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void getAccountStatus().then(status => setSetupRequired(status.setup_required)).catch(() => setError("Cathedra could not reach the local service.")); }, []);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); const username = String(data.get("username") || "").trim(); const password = String(data.get("password") || ""); if (!username || !password) { setError("Enter your username and password."); return; } if (password.length < 10) { setError("Use a password with at least 10 characters."); return; } setBusy(true); try { saveSession(setupRequired ? await setupAdmin(username, password) : await signIn(username, password)); navigate("/"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to sign in."); } finally { setBusy(false); } };
  return <div className="login-page"><div className="login-panel"><div className="login-brand"><div className="brand-mark large">CA</div><div><h1>Cathedra</h1><p>Management Information System</p></div></div><div className="login-copy"><span className="eyebrow">LOCAL OFFICE ACCESS</span><h2>{setupRequired ? "Set up the first administrator" : "Sign in to Cathedra"}</h2><p>{setupRequired ? "Create the first local administrator account for this computer. Keep these details somewhere safe." : "Use your local Cathedra account to access office records."}</p></div><form onSubmit={(event) => void submit(event)} className="login-form"><label>Username<input name="username" autoComplete="username" placeholder="Enter username" /></label><label>Password<input name="password" type="password" autoComplete={setupRequired ? "new-password" : "current-password"} placeholder="At least 10 characters" /></label>{error && <div className="form-error">{error}</div>}<button className="btn primary wide" type="submit" disabled={busy || setupRequired === null}>{busy ? "Please wait…" : setupRequired ? "Create Administrator" : "Sign In"}</button></form>{setupRequired && <div className="dev-note"><strong>First-time setup:</strong> this account can add office staff accounts and manage backups.</div>}</div><div className="login-visual"><div className="visual-orb one"/><div className="visual-orb two"/><div className="visual-content"><span className="eyebrow light">CATHEDRA</span><h2>One protected,<br/>local workspace.</h2><p>Records and backups stay on this computer.</p><div className="visual-modules"><span>01 &nbsp; FSDP</span><span>02 &nbsp; Workload</span><span>03 &nbsp; Backups</span></div></div></div></div>;
}
