import type { ActivityEvent, BackupResult, ExpenseProjection, FacultyProfile, FacultyProfilePayload, FacultyWorkload, FacultyWorkloadPayload, FsdpSummary, GrantReview, GrantType, LocalUser, MaintenanceStatus, PagedResult, SalaryGradeRule, Scholar, ScholarPayload, SessionResult, WorkloadSummary } from "./types";

const API = import.meta.env.DEV ? "http://127.0.0.1:8100/api/v1" : "/api/v1";
const sessionKey = "cathedra-session";
export const getSessionToken = () => localStorage.getItem(sessionKey);
export const saveSession = (result: SessionResult) => localStorage.setItem(sessionKey, JSON.stringify(result));
export const clearSession = () => localStorage.removeItem(sessionKey);
export const getCurrentUser = () => { try { return JSON.parse(getSessionToken() || "").user as LocalUser; } catch { return null; } };
async function request<T>(path: string, init?: RequestInit): Promise<T> { const session = getSessionToken(); const token = session ? JSON.parse(session).token as string : ""; const response = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(init?.headers || {}) }, ...init }); if (!response.ok) { const body = await response.json().catch(() => ({ detail: "Request failed" })); if (response.status === 401) clearSession(); throw new Error(typeof body.detail === "string" ? body.detail : "Please review the fields."); } return response.status === 204 ? undefined as T : response.json() as Promise<T>; }
export const getAccountStatus = () => request<{setup_required:boolean}>("/auth/status"); export const setupAdmin = (username:string, password:string) => request<SessionResult>("/auth/setup", {method:"POST",body:JSON.stringify({username,password})}); export const signIn = (username:string, password:string) => request<SessionResult>("/auth/login", {method:"POST",body:JSON.stringify({username,password})}); export const signOut = () => request<void>("/auth/logout", {method:"POST"}); export const getUsers = () => request<LocalUser[]>("/auth/users"); export const createUser = (username:string,password:string,role:"admin"|"staff") => request<LocalUser>("/auth/users", {method:"POST",body:JSON.stringify({username,password,role})}); export const changePassword = (current_password:string,new_password:string) => request<void>("/auth/change-password",{method:"POST",body:JSON.stringify({current_password,new_password})}); export const resetUserPassword = (id:number,new_password:string) => request<void>(`/auth/users/${id}/reset-password`,{method:"POST",body:JSON.stringify({new_password})});
export const getFsdpRecords = (search = "", status = "", page = 1) => request<PagedResult<Scholar>>(`/fsdp/page?${new URLSearchParams({ search, status, page: String(page), page_size: "50" })}`); export const getFsdpSummary = () => request<FsdpSummary>("/fsdp/summary"); export const getFsdpRecord = (id: number) => request<Scholar>(`/fsdp/${id}`); export const createFsdpRecord = (payload: ScholarPayload) => request<Scholar>("/fsdp", { method: "POST", body: JSON.stringify(payload) }); export const updateFsdpRecord = (id: number, payload: ScholarPayload) => request<Scholar>(`/fsdp/${id}`, { method: "PUT", body: JSON.stringify(payload) }); export const deleteFsdpRecord = (id: number) => request<void>(`/fsdp/${id}`, { method: "DELETE" });
export const getWorkloads = (search = "", academicYear = "", term = "", college = "", page = 1) => request<PagedResult<FacultyWorkload>>(`/workloads/page?${new URLSearchParams({ search, academic_year: academicYear, term, college, page: String(page), page_size: "50" })}`); export const getWorkloadSummary = () => request<WorkloadSummary>("/workloads/summary"); export const getWorkload = (id: number) => request<FacultyWorkload>(`/workloads/${id}`); export const createWorkload = (payload: FacultyWorkloadPayload) => request<FacultyWorkload>("/workloads", { method: "POST", body: JSON.stringify(payload) }); export const updateWorkload = (id: number, payload: FacultyWorkloadPayload) => request<FacultyWorkload>(`/workloads/${id}`, { method: "PUT", body: JSON.stringify(payload) }); export const deleteWorkload = (id: number) => request<void>(`/workloads/${id}`, { method: "DELETE" });
export const getFacultyProfiles = (search = "", page = 1) => request<PagedResult<FacultyProfile>>(`/faculty-profiles/page?${new URLSearchParams({search, page: String(page), page_size: "50"})}`); export const createFacultyProfile = (payload: FacultyProfilePayload) => request<FacultyProfile>("/faculty-profiles", {method:"POST",body:JSON.stringify(payload)}); export const updateFacultyProfile = (id:number,payload:FacultyProfilePayload) => request<FacultyProfile>(`/faculty-profiles/${id}`,{method:"PUT",body:JSON.stringify(payload)}); export const deleteFacultyProfile = (id:number) => request<void>(`/faculty-profiles/${id}`,{method:"DELETE"});
export const getFacultyProfileOptions = () => request<FacultyProfile[]>("/faculty-profiles");
export const getMaintenanceStatus = () => request<MaintenanceStatus>("/maintenance/status"); export const createDatabaseBackup = () => request<BackupResult>("/maintenance/backups", { method: "POST" }); export const restoreDatabase = (filename:string) => request<{restored_from:string;safety_backup:string}>("/maintenance/restore", {method:"POST",body:JSON.stringify({filename})});
export const getSalaryGradeRules = () => request<SalaryGradeRule[]>("/expenses/rules"); export const saveSalaryGradeRule = (rule: Omit<SalaryGradeRule,"id"|"updated_at">) => request<SalaryGradeRule>(`/expenses/rules/${encodeURIComponent(rule.salary_grade)}`,{method:"PUT",body:JSON.stringify(rule)}); export const getExpenseProjection = (academicYear:string,term:string,weeks:number,months:number) => request<ExpenseProjection>(`/expenses/projection?${new URLSearchParams({academic_year:academicYear,term,teaching_weeks:String(weeks),salary_months:String(months)})}`);
export const getActivity = () => request<ActivityEvent[]>("/activity");
export const getGrantReviews = (state: "pending" | "all" = "pending") => request<GrantReview[]>(`/fsdp/grant-reviews?${new URLSearchParams({ state })}`); export const standardizeGrant = (participationId: number, grantType: GrantType, note: string) => request<GrantReview>(`/fsdp/grant-reviews/${participationId}`, { method: "PUT", body: JSON.stringify({ grant_type: grantType, note }) });
export async function downloadExport(kind: "fsdp" | "faculty-profiles" | "workloads", filename: string) { const session = getSessionToken(); const token = session ? JSON.parse(session).token as string : ""; const response = await fetch(`${API}/maintenance/exports/${kind}.csv`, {headers: token ? {Authorization:`Bearer ${token}`} : {}}); if (!response.ok) { const body = await response.json().catch(() => ({ detail: "Unable to export CSV." })); throw new Error(typeof body.detail === "string" ? body.detail : "Unable to export CSV."); } const url = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); }
